services:
  - type: web
    name: telegram-doc-checker
    env: node
    root: ./
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false 