services:
  - type: worker
    name: telegram-doc-checker
    env: node
    root: ./
    buildCommand: npm install
    startCommand: npm run check-deps && node src/index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true 