services:
  - type: web
    name: telegram-doc-checker
    env: node
    plan: starter
    root: ./
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /status
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: RENDER_SERVICE_NAME
        value: telegram-doc-checker 