@echo off
echo Запуск Telegram Doc Checker бота...
echo Останавливаем ранее запущенные экземпляры бота...
taskkill /F /IM node.exe >nul 2>&1
echo Запускаем новый экземпляр бота...
node src/index.js
pause 