@echo off
echo Запуск Telegram Doc Checker бота...
echo Останавливаем ранее запущенные экземпляры бота...
taskkill /F /IM node.exe 2>nul
echo Запускаем новый экземпляр бота...
node src/index.js
pause 